line-length = 79


# Treat .py.jinja files as Python for formatting/linting, 
# Jinja syntax ({% if %}, etc.) inside a .py file will raise a parsing error, so these must still be manually checked. (i.e. __init__.py.jinja)
include = ["*.py", "*.pyi", "*.py*.jinja"]
exclude = [
    "template/src/{{module_name}}/__init__.py.jinja",
    "template/tests/{% if include_reader_plugin %}test_reader.py{% endif %}.jinja",
    "template/tests/{% if include_widget_plugin %}test_widget.py{% endif %}.jinja",
]

[format]
quote-style = "single"

[lint]
select = [
    "E", "F", "W", #flake8
    "UP", # pyupgrade
    "I", # isort
    "BLE", # flake8-blind-exception
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
]
ignore = [
    "E501", # line too long. handled by formatter
    "UP006", "UP007", # type annotation. As using magicgui require runtime type annotation then we disable this.
]
